[package]
name = "varfish-server-worker"
version = "0.5.1"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based workers for varfish-server"
license-file = "LICENSE.md"
homepage = "https://github.com/bihealth/varfish-server-workers"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.0"
anyhow = { version = "1.0.68", features = ["backtrace"] }
base16ct = "0.1.1"
bio = "1.1.0"
byte-unit = "4.0.18"
clap = { version = "4.1.1", features = ["derive", "help"] }
clap-verbosity-flag = "2.0.0"
console = "0.15.5"
csv = "1.1.6"
enum-map = { version = "2.4.2", features = ["serde"] }
env_logger = "0.10.0"
flatbuffers = "23.1.21"
flate2 = "1.0.25"
hpo = "0.7.0"
indexmap = { version = "1.9.2", features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.17"
md-5 = "0.10.5"
memmap2 = "0.5.8"
multimap = "0.8.3"
procfs = "0.14.2"
regex = "1.7.1"
result = "1.0.0"
rust-htslib = { version = "0.40.2", default-features = false }
serde = { version = "1.0.152", features = ["serde_derive"] }
serde-jsonlines = "0.4.0"
serde_json = "1.0.91"
sha2 = "0.10.6"
shellexpand = "3.0.0"
strum = "0.24.1"
strum_macros = "0.24.3"
tempdir = "0.3.7"
thiserror = "1.0.38"
thousands = "0.2.0"
toml = { version = "0.6.0", features = ["preserve_order", "parse", "display"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
uuid = { version = "1.2.2", features = ["v4", "fast-rng", "serde"] }

[build-dependencies]
flatc-rust = "0.2.0"

[dev-dependencies]
file_diff = "1.0.0"
serde_test = "1.0.152"
pretty_assertions = "1"
temp_testdir = "0.2"

[[bin]]
name = "varfish-server-worker"
path = "src/main.rs"
