[package]
name = "varfish-server-worker"
version = "0.9.0"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based workers for varfish-server"
license = "MIT"
homepage = "https://github.com/bihealth/varfish-server-workers"
edition = "2021"
readme = "README.md"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annonars = "0.12"
anyhow = { version = "1.0", features = ["backtrace"] }
base16ct = "0.2"
bio = "1.1"
byte-unit = "4.0"
chrono = { version = "0.4", features = ["serde"] }
clap-verbosity-flag = "2.0"
clap = { version = "4.3", features = ["derive", "help"] }
console = "0.15"
csv = "1.1"
enum-map = { version = "2.4", features = ["serde"] }
fastrand = "2.0"
flate2 = "1.0"
hgvs = "0.10"
indexmap = { version = "2.0", features = ["serde"] }
itertools = "0.11"
lazy_static = "1.4"
log = "0.4"
mehari = "0.6"
multimap = "0.9"
procfs = "0.15"
prost = "0.11"
regex = "1.9"
serde_json = "1.0"
serde-jsonlines = "0.4"
serde = { version = "1.0", features = ["serde_derive"] }
serde_with = "3.0"
shellexpand = "3.0"
strum_macros = "0.25"
strum = { version = "0.25", features = ["derive"] }
tempdir = "0.3"
thiserror = "1.0"
thousands = "0.2"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.2", features = ["v4", "fast-rng", "serde"] }


[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
file_diff = "1.0"
float-cmp = "0.9.0"
insta = { version = "1.29", features = ["yaml"] }
pretty_assertions = "1.4"
rstest = "0.18.0"
serde_test = "1.0"
temp_testdir = "0.2"

[[bin]]
name = "varfish-server-worker"
path = "src/main.rs"
