[package]
name = "varfish-server-worker"
version = "0.6.1"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based workers for varfish-server"
license = "MIT"
homepage = "https://github.com/bihealth/varfish-server-workers"
edition = "2021"
readme = "README.md"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6"
actix-web = "4.3"
annonars = "0.5"
anyhow = { version = "1.0", features = ["backtrace"] }
base16ct = "0.2"
bgzip = "0.3"
bio = "1.1"
byte-unit = "4.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.1", features = ["derive", "help"] }
clap-verbosity-flag = "2.0"
console = "0.15"
csv = "1.1"
derive_more = "0.99"
enum-map = { version = "2.4", features = ["serde"] }
env_logger = "0.10"
fastrand = "1.9"
flatbuffers = "23.1"
flate2 = "1.0"
hgvs = "0.8"
hpo = "0.8"
indexmap = { version = "1.9", features = ["serde"] }
indicatif = { version = "0.17", features = ["rayon"] }
itertools = "0.10"
lazy_static = "1.4"
linked-hash-map = { version = "0.5", features = ["serde", "serde_impl"] }
log = "0.4"
md-5 = "0.10"
memmap2 = "0.6"
multimap = "0.9"
noodles-bgzf = "0.21"
noodles-core = "0.11"
noodles-csi = "0.18"
noodles-tabix = "0.21"
noodles-vcf = "0.30"
procfs = "0.15"
prost = "0.11"
rayon = "1.7"
regex = "1.7"
result = "1.0"
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde-jsonlines = "0.4"
serde_json = "1.0"
serde_with = "3.0"
sha2 = "0.10"
shellexpand = "3.0"
strum = "0.24"
strum_macros = "0.24"
tempdir = "0.3"
thiserror = "1.0"
thousands = "0.2"
toml = { version = "0.7", features = ["preserve_order", "parse", "display"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.2", features = ["v4", "fast-rng", "serde"] }

[build-dependencies]
flatc-rust = "0.2"
prost-build = "0.11"

[dev-dependencies]
file_diff = "1.0"
serde_test = "1.0"
pretty_assertions = "1.3"
temp_testdir = "0.2"
insta = { version = "1.29", features = ["yaml"] }

[[bin]]
name = "varfish-server-worker"
path = "src/main.rs"
