name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install protolint
        run: |
          pip install protolint-bin

      - name: Run protolint
        run: |
          make protolint-check
