on:
  push:
    branches:
      - main
      - release/*

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'bihealth'
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: rust
          package-name: varfish-server-worker

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          toolchain: stable
          override: true

      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v1.3.0
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish crate
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}
